version: '3.5'

services:
  sip-api:
    container_name: sip-api
    image: sip-api
    build: .
    volumes:
      - sip-bundle-cache-volume:/bundle
      - sip-api-volume:/opt/app
    environment:
      - APP_ENV=development
      - DB_HOST=sip-db
      - DB_USERNAME=postgres
    command: bundle exec rails s
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sip-network
    depends_on:
      - sip-db

  sip-db:
    image: postgres
    restart: always
    volumes:
      - sip-database-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
    networks:
      - sip-network

networks:
  sip-network:
    name: sip-network

volumes:
  sip-api-volume:
    name: sip-api-volume
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
  sip-database-volume:
  sip-bundle-cache-volume:
